name: instagram_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^0.13.4+2
  font_awesome_flutter: ^8.0.1
  flutter_staggered_grid_view: ^0.3.0
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.12
  carousel_pro: ^1.0.0
  scoped_model: ^1.0.1
  path_provider: ^1.6.5
  firebase_auth: ^0.15.5+2
  url_launcher: ^5.4.2
  transparent_image: ^1.0.0
  bloc: ^3.0.0
  intl: ^0.16.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/insta_logo.png
  uses-material-design: true

